spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5433/app_db
    username: user
    password: 123
    hikari:
      schema: app_schema
      connection-ini-sql: CREATE SCHEMA IF NOT EXISTS app_schema
      connection-timeout: 10000
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9892
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/appdatabase?authSource=admin

app:
  kafka:
    kafkaUserTopic: "user-topic"
    kafkaBookingTopic: "booking-topic"
    kafkaBookingGroupId: "kafka-group-id"
